version: '3.8'

services:
  node_modules:
    container_name: node_modules-${ENVIRONMENT}
    build: ./
    volumes:
      - node_modules:/app/node_modules
  tag-system:
    container_name: editor_hub_tag_system_${ENVIRONMENT}
    build: ./packages/tag-system
    volumes:
      - tag-system:/app/packages/tag-system
  dropbox-types:
    container_name: editor_hub_dropbox_types_${ENVIRONMENT}
    build: ./packages/dropbox-types
    volumes:
      - dropbox-types:/app/packages/dropbox-types
  api-sdk:
    container_name: editor_hub_api_sdk_${ENVIRONMENT}
    build: ./packages/api-sdk
    volumes:
      - node_modules:/app/node_modules
      - tag-system:/app/packages/tag-system
      - dropbox-types:/app/packages/dropbox-types
      - api-sdk:/app/packages/api-sdk
    depends_on:
      - node_modules
      - tag-system
      - dropbox-types
  server:
    container_name: editor-hub-server-${ENVIRONMENT}
    build: ./server
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - node_modules:/app/node_modules
      - tag-system:/app/packages/tag-system
      - dropbox-types:/app/packages/dropbox-types
      - api-sdk:/app/packages/api-sdk
      - auth-app:/app/apps/authorization/dist
      - ./authCode:/app/authCode
      - clip-tagger:/app/public/clip-tagger
      - editor-hub:/app/public/editor-hub
    depends_on:
      - node_modules
      - tag-system
      - dropbox-types
      - authorization
      - clip-tagger
      - editor-hub
  authorization:
    container_name: authorization-${ENVIRONMENT}
    build: ./apps/authorization
    working_dir: /app
    volumes:
      - node_modules:/app/node_modules
      - auth-app:/app/dist
    depends_on:
      - node_modules
  clip-tagger:
    container_name: clip-tagger-${ENVIRONMENT}
    build: ./apps/clip-tagger
    volumes:
      - node_modules:/app/node_modules
      - tag-system:/app/packages/tag-system
      - dropbox-types:/app/packages/dropbox-types
      - api-sdk:/app/packages/api-sdk
      - clip-tagger:/app/dist
    depends_on:
      - node_modules
      - tag-system
      - dropbox-types
      - api-sdk
  editor-hub:
    container_name: editor-hub-${ENVIRONMENT}
    build: ./apps/editor-hub
    volumes:
      - node_modules:/app/node_modules
      - tag-system:/app/packages/tag-system
      - dropbox-types:/app/packages/dropbox-types
      - api-sdk:/app/packages/api-sdk
      - editor-hub:/app/dist
    depends_on:
      - node_modules
      - tag-system
      - dropbox-types
      - api-sdk
volumes:
  auth-app:
  clip-tagger:
  editor-hub:
  node_modules:
  tag-system:
  dropbox-types:
  api-sdk: