version: '3.8'

services:
  server:
    container_name: ${SERVER_CONTAINER_NAME:-editor-hub}
    build: .
    ports:
      - "5100:5100"
    restart: always
    working_dir: /app
    volumes:
      - ./public/jsonFiles:/app/public/jsonFiles
      - ./public/modules:/app/public/modules
      - ./public/resources:/app/public/resources
      - auth-app:/app/apps/authorization/dist
      - ./authCode:/app/authCode
      - clip-tagger:/app/public/clip-tagger
    depends_on:
      - authorization
      - clip-tagger
  authorization:
    container_name: ${AUTH_CONTAINER_NAME:-authorization}
    build: ./apps/authorization
    working_dir: /app
    volumes:
      - auth-app:/app/dist
  clip-tagger:
    container_name: ${CLIP_TAGGER_CONTAINER_NAME:-clip-tagger}
    build: ./apps/clip-tagger
    working_dir: /app
    volumes:
      - clip-tagger:/app/dist
volumes:
  auth-app:
  clip-tagger: