version: '3.8'

services:
  dependencies:
    container_name: dependencies-${ENVIRONMENT}
    working_dir: /app
    build:
      context: ./
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
    command: ["bun", "run", "build:libs"]
    volumes:
      - node_modules:/app/node_modules
      - libs:/app/libs
  server:
    container_name: editor-hub-server-${ENVIRONMENT}
    working_dir: /app
    build:
      context: ./server
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
    command: ["bun", "run", "serve"]
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - node_modules:/app/node_modules
      - libs:/app/libs
      - auth-app:/app/apps/authorization/dist
      - clip-tagger:/app/public/clip-tagger
      - editor-hub:/app/public/editor-hub
      - ./authCode:/app/authCode
    depends_on:
      - dependencies
      - authorization
      - clip-tagger
      - editor-hub
  authorization:
    container_name: authorization-${ENVIRONMENT}
    working_dir: /app
    build:
      context: ./apps/authorization
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - node_modules:/app/node_modules
      - auth-app:/app/dist
    depends_on:
      - dependencies
  clip-tagger:
    container_name: clip-tagger-${ENVIRONMENT}
    working_dir: /app
    build:
      context: ./apps/clip-tagger
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - node_modules:/app/node_modules
      - libs:/app/libs
      - clip-tagger:/app/dist
    depends_on:
      - dependencies
  editor-hub:
    container_name: editor-hub-${ENVIRONMENT}
    working_dir: /app
    build:
      context: ./apps/editor-hub
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - node_modules:/app/node_modules
      - libs:/app/libs
      - editor-hub:/app/dist
    depends_on:
      - dependencies
volumes:
  auth-app:
  clip-tagger:
  editor-hub:
  node_modules:
  libs: