version: '3.8'

services:
  server:
    container_name: editor-hub-server-${ENVIRONMENT}
    build: ./server
    ports:
      - "${PORT}:${PORT}"
    restart: always
    working_dir: /app
    volumes:
      - ./public/jsonFiles:/app/public/jsonFiles
      - ./public/modules:/app/public/modules
      - ./public/resources:/app/public/resources
      - auth-app:/app/apps/authorization/dist
      - ./authCode:/app/authCode
      - clip-tagger:/app/public/clip-tagger
      - editor-hub:/app/public/editor-hub
    depends_on:
      - authorization
      - clip-tagger
  authorization:
    container_name: authorization-${ENVIRONMENT}
    build: ./apps/authorization
    working_dir: /app
    volumes:
      - auth-app:/app/dist
  clip-tagger:
    container_name: clip-tagger-${ENVIRONMENT}
    build: ./apps/clip-tagger
    working_dir: /app
    volumes:
      - clip-tagger:/app/dist
  editor-hub:
    container_name: editor-hub-${ENVIRONMENT}
    build: ./apps/editor-hub
    working_dir: /app
    volumes:
      - editor-hub:/app/dist
volumes:
  auth-app:
  clip-tagger:
  editor-hub: