version: '3.8'

services:
  dependencies:
    container_name: dependencies-${ENVIRONMENT}
    build:
      context: ./
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
        RUN chmod +x ./workflows/*
    command: ["bun", "run", "build:libs"]
    volumes:
      - root_node_modules:/app/node_modules
      - server_node_modules:/app/server/node_modules
      - clip-tagger_node_modules:/app/apps/clip-tagger/node_modules
      - editor-hub_node_modules:/app/apps/editor-hub/node_modules
      - libs:/app/libs
  server:
    container_name: editor-hub-server-${ENVIRONMENT}
    build:
      context: ./server
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app/server
        COPY . .
    command: ["bun", "run", "serve"]
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - root_node_modules:/app/node_modules
      - server_node_modules:/app/server/node_modules
      - libs:/app/libs
      - landing:/app/server/public/landing
      - auth-app:/app//server/apps/authorization/dist
      - clip-tagger:/app/server/public/clip-tagger
      - editor-hub:/app/server/public/editor-hub
      - project-manager:/app/server/public/project-manager
      - ./authCode:/app/server/authCode
    depends_on:
      dependencies:
        condition: service_completed_successfully
      landing:
        condition: service_started
      authorization:
        condition: service_started
      clip-tagger:
        condition: service_started
      editor-hub:
        condition: service_started
      project-manager:
        condition: service_started
  landing:
    container_name: landing-${ENVIRONMENT}
    build:
      context: ./apps/landing
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app/landing
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - root_node_modules:/app/node_modules
      - landing_node_modules:/app/landing/node_modules
      - libs:/app/libs
      - landing:/app/landing/dist
    depends_on:
      dependencies:
        condition: service_completed_successfully
  authorization:
    container_name: authorization-${ENVIRONMENT}
    build:
      context: ./apps/authorization
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - root_node_modules:/app/node_modules
      - auth-app:/app/dist
    depends_on:
      dependencies:
        condition: service_completed_successfully
  clip-tagger:
    container_name: clip-tagger-${ENVIRONMENT}
    build:
      context: ./apps/clip-tagger
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app/clip-tagger
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - root_node_modules:/app/node_modules
      - clip-tagger_node_modules:/app/clip-tagger/node_modules
      - libs:/app/libs
      - clip-tagger:/app/clip-tagger/dist
    depends_on:
      dependencies:
        condition: service_completed_successfully
  editor-hub:
    container_name: editor-hub-${ENVIRONMENT}
    build:
      context: ./apps/editor-hub
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app/editor-hub
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - root_node_modules:/app/node_modules
      - editor-hub_node_modules:/app/editor-hub/node_modules
      - libs:/app/libs
      - editor-hub:/app/editor-hub/dist
    depends_on:
      dependencies:
        condition: service_completed_successfully
  project-manager:
    container_name: project-manager-${ENVIRONMENT}
    build:
      context: ./apps/project-manager
      dockerfile_inline: |
        FROM oven/bun
        WORKDIR /app/project-manager
        COPY . .
    command: ["bun", "run", "build"]
    volumes:
      - root_node_modules:/app/node_modules
      - project-manager_node_modules:/app/project-manager/node_modules
      - libs:/app/libs
      - project-manager:/app/project-manager/dist
    depends_on:
      dependencies:
        condition: service_completed_successfully
volumes:
  landing:
  auth-app:
  clip-tagger:
  editor-hub:
  project-manager:
  root_node_modules:
  landing_node_modules:
  server_node_modules:
  clip-tagger_node_modules:
  editor-hub_node_modules:
  project-manager_node_modules:
  libs: