version: '3.8'

services:
  server:
    container_name: editor-hub
    build: .
    ports:
      - "5100:5100"
    restart: always
    working_dir: /app
    volumes:
      - ./public:/app/public
      - auth-app:/app/apps/authorization/dist
    depends_on:
      - authorization
  authorization:
    container_name: authorization
    build: ./apps/authorization
    working_dir: /app
    volumes:
      - auth-app:/app/dist
volumes:
  auth-app: