name: Deploy to Production and Development

on:
  push:
    branches:
      - main
      - dev
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EDITOR_HUB_HOST }}
        username: ${{ secrets.EDITOR_HUB_USER }}
        key: ${{ secrets.EDITOR_HUB_KEY }}

    - name: Deploy to production
      if: endsWith(github.ref, '/main')
      run: |
        pwd
        echo ${{ secrets.EDITOR_HUB_PRODUCTION_DIR }}
        cd ${{ secrets.EDITOR_HUB_PRODUCTION_DIR }}
        npm run deploy
    - name: Deploy to dev
      if: endsWith(github.ref, '/dev')
      run: |
        cd ${{ secrets.EDITOR_HUB_DEV_DIR }}
        npm run deploy