name: Deploy to Production and Development

on:
  push:
    branches:
      - main     # For production deployment
      - dev      # For development deployment
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EDITOR_HUB_HOST }}
        passphrase: ${{ secrets.EDITOR_HUB_PASSPHRASE }}
        key: ${{ secrets.EDITOR_HUB_KEY }}

    - name: Deploy
      run: |
        if [ "${GITHUB_REF##*/}" == "main" ]; then
          echo "Deploying to Production..."
          DEPLOY_FOLDER=${{ secrets.EDITOR_HUB_PRODUCTION_DIR }}
        else
          echo "Deploying to Development..."
          DEPLOY_FOLDER=${{ secrets.EDITOR_HUB_DEV_DIR }}
        fi
        cd $DEPLOY_FOLDER
        npm run deploy
        EOF
