name: Deploy to Production and Development

on:
  push:
    branches:
      - main     # For production deployment
      - dev      # For development deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EDITOR_HUB_GITHUB_ACTIONS }}

    - name: Install dependencies and deploy
      run: |
        if [ "${GITHUB_REF##*/}" == "main" ]; then
          echo "Deploying to Production..."
          DEPLOY_FOLDER="/home/servers/skillcapped/editor-hub/production"
        else
          echo "Deploying to Development..."
          DEPLOY_FOLDER="/home/servers/skillcapped/editor-hub/dev"
        fi

        # SSH into the VPS and deploy
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@ralvar.com << EOF
          cd $DEPLOY_FOLDER
          npm run deploy
        EOF
